// <auto-generated />
namespace GiftManagerWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changetypetodatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetypetodatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "202012152055191_change-type-to-date-time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
